dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: maybethenamewasbad
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: so-you-really-hate-underscore-jx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
